version: '3'

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - ${NS_MONGO_DATA_DIR:-./mongo-data}:/data/db:cached

  nightscout:
    image: nightscout:relative
    container_name: nightscout
    restart: always
    depends_on:
      - mongo
    labels:
      # Replace localhost with your domain
      caddy: localhost

      # If you want to serve nightscout in a subdirectory behind a reverse proxy, uncomment this.
      # If you want to use a different subdirectory than 'nightscout', replace
      # 'nightscout' with the name of your desired subdirectory.
#      caddy.redir: '/nightscout /nightscout/'
#      caddy.handle_path: '/nightscout/*'
#      caddy.handle_path.reverse_proxy: '{{upstreams 1337}}'
#      caddy.handle: '/socket.io*'
#      caddy.handle.reverse_proxy: '{{upstreams 1337}}'
    environment:
      ### Variables for the container
      NODE_ENV: production
      TZ: Etc/UTC

      ### Overridden variables for Docker Compose setup
      # The `nightscout` service can use HTTP, because we use `traefik` to serve the HTTPS
      # and manage TLS certificates
      INSECURE_USE_HTTP: 'true'

      # For all other settings, please refer to the Environment section of the README
      ### Required variables
      # MONGO_CONNECTION - The connection string for your Mongo database.
      # Something like mongodb://sally:sallypass@ds099999.mongolab.com:99999/nightscout
      # The default connects to the `mongo` included in this docker-compose file.
      # If you change it, you probably also want to comment out the entire `mongo` service block
      # and `depends_on` block above.
      MONGO_CONNECTION: mongodb://mongo:27017/nightscout

      # API_SECRET - A secret passphrase that must be at least 12 characters long.
      API_SECRET: 123456789abc

      ### Features
      # ENABLE - Used to enable optional features, expects a space delimited list, such as: careportal rawbg iob
      # See https://github.com/nightscout/cgm-remote-monitor#plugins for details
      ENABLE: careportal rawbg iob

      # AUTH_DEFAULT_ROLES (readable) - possible values readable, denied, or any valid role name.
      # When readable, anyone can view Nightscout without a token. Setting it to denied will require
      # a token from every visit, using status-only will enable api-secret based login.
      AUTH_DEFAULT_ROLES: denied

      # For all other settings, please refer to the Environment section of the README
      # https://github.com/nightscout/cgm-remote-monitor#environment

  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.7-alpine
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
    restart: unless-stopped
